name: hello-world
on: 
  push:
  pull_request:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: org
        run: echo "Hello O RG ORG [${{ secrets.ORG }}] ORG OR G"
      - name: user
        run: echo "Hello U SR USR ${{ secrets.USR }} USR US R"
      - name: shared
        run: echo "Hello S HR SHR ${{ secrets.SHR }} SHR SH R"

